### ISSUE TITLE
Support for newer LLVM versions?

### ISSUE THREAD

**Issue by jcarlson23** [caballa/crab-llvm#13]
Hello, I went to start using this but I'm using LLVM 4 (and 3.8) locally but it looks like in the CMakeLists.txt crab-llvm is expecting 3.6?  generally, that's a pretty good sized jump I would expect but is it true that > 3.6 would be not be expected to work?  And if so, any ideas just how painful updating it might be?  (rough estimate is fine, I'm just trying to scope how much time it might take if I was daring enough to try to help do that...)

Thank you!

**Comment by caballa** [comment]
Yes, the code expects LLVM 3.6. With 3.8 is not expected to work. If you are familiar with LLVM source code porting shouldn't be hard. Maybe few hours. Port at least to 3.8 is on my TODO list, I just need some free cycles.

**Comment by jcarlson23** [comment]
ok, thanks!  I might start in on a 4.0 port then, see how much headway I can make - good way to learn the source as well I figure...
