### ISSUE TITLE
type 

### ISSUE THREAD

**Issue by jcarlson23** [caballa/crab-llvm#14]
@caballa I started in on a port and things are going along fairly well, except I ran into the following:

```
/tmp/llvm-4.0.0.src/include/llvm/ADT/STLExtras.h:139:13: error: no type named 'type' in 'std::__1::result_of<std::__1::pointer_to_unary_function<llvm::DSNode *, llvm::DSNode &>
      (llvm::DSNode &)>'
          ::type value_type;
          ~~^~~~
/tmp/Projects/crab-llvm/dsa-seahorn/include/dsa/DSGraphTraits.h:119:25: note: in instantiation of template class
      'llvm::mapped_iterator<llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::DSNode, true, false, void>, false, false>, std::__1::pointer_to_unary_function<llvm::DSNode *, llvm::DSNode &> >'
      requested here
  static nodes_iterator nodes_begin(DSGraph *G) {
                        ^
1 error generated.
```

So looks like the DSNode type can't be dereferenced fully with supplying a type?  I'm not used to the usage of pointer_to_unary_function in custom classes.  Looks like this might need to be a static typedef??  I'm a little unsure so figured it was worth asking...  Thanks, no rush.  CMake is telling me I'm 14% of the way through the compilation...

**Comment by octomagon** [comment]
I know in LLVM 4.0 the NodeType becomes a NodeRef, which _HAS_ to be a pointer, so perhaps your indirection has some inconsistencies?

**Comment by jcarlson23** [comment]
No...  I don't think so, I tried changing back the NodeRef to a NodeType without a pointer and I got the same error (where I was expecting to see the static_assert error - as seen in the LLVM src).  I need to have a type for the function adapter I think, I'm just not that familiar with this pattern..  I need to brush on some STL...

**Comment by jcarlson23** [comment]
Alright I got this to compile as the NodeRef must be a pointer so I don't _think_ that the dereferencing is necessary or wanted... that said, we'll see when get around..  But for now it's compiling and I'm up to 15% of compilation.
