### ISSUE TITLE
If it is possible to output the domain in the format of constraints or generator?

### ISSUE THREAD

**Issue by gaobo89** [caballa/crab-llvm#15]
as titled, If it is possible to output the domain in the format of constraints or generator?
for example, 
--crab --crab-domain=int(or pk_apron)
if i want to get the polyhedra domain of newpolka or interval, is that possible?

thanks a lot.

**Comment by caballa** [comment]
There is a method `to_linear_constraint_system` that does that.

**Comment by caballa** [comment]
@gaobo89: can I close the issue?
