### ISSUE TITLE
A question about the output form of invariant from crab-llvm

### ISSUE THREAD

**Issue by gaobo89** [caballa/crab-llvm#16]
Dear holders, I have a problem understanding the output invariant of crab-llvm, such as followings:

![capture1](https://user-images.githubusercontent.com/28553281/27811706-b11fe6ae-609b-11e7-9197-0ebbeaec26ff.JPG)

what do these lines mean? 
if I want to get the invariant, I just concentrate on the .lcssa items of x and y, right?
But what should I do if I encounter the following situations, there is no clue about the x and y? 
thank you for your kindness.

![capture2](https://user-images.githubusercontent.com/28553281/27811817-a7558e48-609c-11e7-9acb-4bed685598e2.JPG)

**Comment by caballa** [comment]
For each function it outputs something following this grammar:

`(BASIC_BLOCK: "{" CONSTRAINTS "}")*`

`BASIC_BLOCK` is just the basic block name from the analyzed LLVM bitcode
`CONSTRAINTS` is a sequence (conjunction) of linear constraints. These are the constraints (invariants) that hold when the execution reaches the entry of `BASIC_BLOCK`.

For instance, 

`.lr.ph : { x.0.i1- _3  = 1; -_1+_3+_4 = 0; -_1+y.0.i2 + _3 = -1; -_1 + _3 <= -1}`

it says that at the entry of block `.lr.ph`  the constraints `x.0.i1 - _3 = 1` and `...` are true.

You seem confused about how to map variables such as `_1`,`_3`, `x.0.i1`, and so on to the original names in the C program. Unfortunately, crab-llvm is an analyzer of llvm bitcode so it doesn't provide such a mapping. This is something you would need to construct by yourself.

**Comment by caballa** [comment]
If you want to know how these LLVM variables are created you can add option `-oll=file.ll` and it will show the exact LLVM bitcode analyzed by crab-llvm. Then, all the variables that appear in the invariants should appear in `file.ll`. In that way, you can make sense of the invariants. But again, this doesn't solve the problem of mapping back to the C names but it will help

**Comment by gaobo89** [comment]
thank you so much, it is very clear, I will try your way and find the C names.

**Comment by gaobo89** [comment]
by the way, the .lcssa items don't mean the invariant all the time, just a normal variable in the output,right?

**Comment by caballa** [comment]
yes, it's just a normal variable. This one is generated by the LCSSA pass.
